spring.thymeleaf.encoding=UTF-8
spring.web.resources.static-locations=classpath:/static/

# =============================
# SQL Server Configuration
# =============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=j6lab2b3;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# =============================
# Hibernate & JPA Configuration
# =============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=8080
spring.security.oauth2.client.registration.google.client-id=943933050730-6dia19geiaahu60topqmq1aup3aub2kq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
